name: Build + Test

on: [push, pull_request]

jobs:
  build-latest:
    name: Run on latest macOS
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clean
      run: make clean
    - name: Build
      run: make build
    - name: Install
      run: 'export PREFIX=$(pwd) && make install'
    - name: Set Up
      run: |
        ./bin/mockingbird install \
          --target MockingbirdTests \
          --source MockingbirdTestsHost \
          --loglevel verbose \
          --verbose
    - name: Test
      run: make clean-test
    - name: Cached Test
      run: make test
