name: Build + Test

on: [push, pull_request]

jobs:
  build-latest:
    name: Run on latest macOS
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print Debug Info
      run: make print-debug-info
    - name: Set Up Project
      run: make setup-project
    - name: Clean
      run: make clean
    - name: Build Framework
      run: make build-framework
    - name: Build and Install CLI
      run: |
        PREFIX=$(pwd) HERMETIC=1 make print-debug-info
        PREFIX=$(pwd) HERMETIC=1 make install
    - name: Set Up Caching Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --diagnostics all \
          --prune stub \
          --verbose
    - name: Test
      run: make clean-test
    - name: Cached Test
      run: make test
    - name: Set Up Non-Caching Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --disable-cache \
          --diagnostics all \
          --prune stub \
          --verbose
    - name: Test Flakiness
      run: make test-flaky
    - name: Set Up Non-Pruning Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --prune disable \
          --disable-cache \
          --diagnostics all \
          --prune disable \
          --verbose
    - name: Test All Thunks
      run: make clean-test
