name: CI

on: [push, pull_request]

jobs:
  endToEnd:
    name: Test Generator and Framework
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Project
      run: Scripts/swift-sh Scripts/ManageProject.swift load --overwrite
    - name: Build Framework
      run: make build-framework
    - name: Build and Install CLI
      run: |
        PREFIX=$(pwd) HERMETIC=1 make print-debug-info
        PREFIX=$(pwd) HERMETIC=1 make install
    - name: Set Up Caching Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --diagnostics all \
          --prune stub \
          --verbose
    - name: Test
      run: make clean-test
    - name: Cached Test
      run: make test
    - name: Set Up Non-Caching Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --disable-cache \
          --diagnostics all \
          --prune stub \
          --verbose
    - name: Test Flakiness
      run: make test-flaky
    - name: Set Up Non-Pruning Target
      run: |
        ./bin/mockingbird configure MockingbirdTests --verbose -- \
          --targets \
            MockingbirdTestsHost \
            MockingbirdShadowedTestsHost \
          --support Sources/MockingbirdSupport \
          --outputs \
            Tests/MockingbirdTests/Mocks/MockingbirdTestsHostMocks.generated.swift \
            Tests/MockingbirdTests/Mocks/MockingbirdShadowedTestsHostMocks.generated.swift \
          --header '// Header line 1' '// Header line 2' \
          --prune disable \
          --disable-cache \
          --diagnostics all \
          --prune disable \
          --verbose
    - name: Test All Thunks
      run: make clean-test

  test-podspec:
    name: Test Podspec
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: pod spec lint MockingbirdFramework.podspec

  test-example-project:
    name: Test Example Project (${{ matrix.type }})
    runs-on: macOS-latest
    strategy:
      matrix:
        type:
        - cocoapods
        - carthage
        - spm-project
        - spm-package
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: Scripts/swift-sh Scripts/TestExampleProject.swift ${{ matrix.type }}
