name: CI

on: [push, pull_request]

jobs:
  test-e2e:
    name: Test E2E
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Project
      run: Scripts/swift-sh Scripts/ManageProject.swift load --overwrite
    - name: Test
      run: Scripts/swift-sh Scripts/RunTest.swift e2e

  test-podspec:
    name: Test Podspec
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: pod spec lint MockingbirdFramework.podspec

  test-example-project:
    name: Test Example Project (${{ matrix.type }})
    runs-on: macOS-latest
    strategy:
      matrix:
        type:
        - cocoapods
        - carthage
        - spm-project
        - spm-package
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: Scripts/swift-sh Scripts/TestExampleProject.swift ${{ matrix.type }}
