name: Release

on:
  push:
    branches:
    - 'master'
    - 'release-*'
    tags:
    - '*'

jobs:
  build:
    name: Build Signed Artifacts
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Set Up Project
      run: Scripts/swift-sh Scripts/ManageProject.swift load --overwrite
    - name: Build CLI
      env:
        AC_USERNAME: ${{ secrets.AC_USERNAME }}
        AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      run: |
        Scripts/swift-sh Scripts/BuildArtifact.swift cli \
          --sign 'Developer ID Application: Bird Rides, Inc. (P2T4T6R4SL)' \
          --archive .build/mockingbird/artifacts/Mockingbird.zip
    - name: Build Framework
      run: |
        Scripts/swift-sh Scripts/BuildArtifact.swift framework \
          --archive .build/mockingbird/artifacts/Mockingbird.xcframework.zip
    - name: Document SHAs
      run: |
        shasum -a 512 .build/mockingbird/artifacts/Mockingbird.zip
        shasum -a 512 .build/mockingbird/artifacts/Mockingbird.xcframework.zip
    - name: Upload CLI
      uses: actions/upload-artifact@v2
      with:
        name: Mockingbird
        path: .build/mockingbird/artifacts/Mockingbird.zip
    - name: Upload Framework
      uses: actions/upload-artifact@v2
      with:
        name: Mockingbird.xcframework
        path: .build/mockingbird/artifacts/Mockingbird.xcframework.zip
