name: Test Example Projects

on:
 push:
  paths:
  - 'Examples/**'
  - '.github/workflows/**'
  - 'Makefile'
 pull_request:
  paths:
  - 'Examples/**'
  - '.github/workflows/**'
  - 'Makefile'

jobs:
  test-cocoapods:
    name: Check CocoaPods integration
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: make clean-cocoapods
    - name: Test
      run: 'PATH=$(pwd)/bin:$PATH make test-cocoapods'
    - name: Cached Test
      run: make test-cocoapods

  test-carthage:
    name: Check Carthage integration
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: make clean-carthage
    - name: Test
      run: 'PATH=$(pwd)/bin:$PATH make test-carthage'
    - name: Cached Test
      run: make test-carthage

  test-spm:
    name: Check SPM integration
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: make clean-spm
    - name: Test
      run: 'PATH=$(pwd)/bin:$PATH make test-spm'
    - name: Cached Test
      run: make test-spm
